import LeanBiscuit.Util.Bytes
import LeanBiscuit.Crypto.Sha512

/-!
# Ed25519 signature verification

The default biscuit signature algorithm, as specified in RFC 8032.  Only
verification is needed to authorize a token, and that is all this module
provides.

Field elements are plain natural numbers reduced modulo `p = 2^255 - 19`, and
curve points use extended twisted Edwards coordinates `(X : Y : Z : T)` with
`x = X/Z`, `y = Y/Z` and `T = XY/Z`.  The verification equation follows the
"strict" variant used by the reference implementation: the scalar must be
canonically reduced, and neither the public key nor the signature's `R` may be
of small order.
-/

namespace LeanBiscuit
namespace Ed25519

/-- The field characteristic, `2^255 - 19`. -/
def p : Nat := 57896044618658097711785492504343953926634992332820282019728792003956564819949

/-- The order of the prime-order subgroup generated by the base point. -/
def L : Nat := 7237005577332262213973186563042994240857116359379907606001950938285454250989

/-- The curve constant `d = -121665/121666`. -/
def d : Nat := 37095705934669439343138083508754565189542113879843219016388785533085940283555

/-- `sqrt(-1)` in the field, used when taking square roots. -/
def sqrtM1 : Nat := 19681161376707505956807079304988542015446066515923890162744021073123829784752

namespace F

@[inline] def add (a b : Nat) : Nat := (a + b) % p
@[inline] def sub (a b : Nat) : Nat := (a + p - b % p) % p
@[inline] def mul (a b : Nat) : Nat := (a * b) % p
@[inline] def neg (a : Nat) : Nat := (p - a % p) % p

/-- Square-and-multiply accumulator for `pow`. -/
def powAux (b e acc : Nat) : Nat :=
  if _h : e = 0 then acc
  else
    powAux (b * b % p) (e / 2) (if e % 2 == 1 then acc * b % p else acc)
termination_by e
decreasing_by exact Nat.div_lt_self (Nat.pos_of_ne_zero _h) (by decide)

/-- Modular exponentiation by square-and-multiply. -/
def pow (base e : Nat) : Nat := powAux (base % p) e 1

/-- Multiplicative inverse, via Fermat's little theorem. -/
def inv (a : Nat) : Nat := pow a (p - 2)

/-- `true` when the least significant bit of the canonical representative is set. -/
@[inline] def isOdd (a : Nat) : Bool := a % 2 == 1

end F

/-- A curve point in extended twisted Edwards coordinates. -/
structure Point where
  X : Nat
  Y : Nat
  Z : Nat
  T : Nat
  deriving Repr

namespace Point

/-- The neutral element `(0, 1)`. -/
def zero : Point := ⟨0, 1, 1, 0⟩

/-- The standard base point. -/
def base : Point :=
  let y := 46316835694926478169428394003475163141307993866256225615783033603165251855960
  let x := 15112221349535400772501151409588531511454012693041857206046113283949847762202
  ⟨x, y, 1, F.mul x y⟩

/-- Point addition, using the unified formulas for `a = -1`. -/
def add (P Q : Point) : Point :=
  let a := F.mul (F.sub P.Y P.X) (F.sub Q.Y Q.X)
  let b := F.mul (F.add P.Y P.X) (F.add Q.Y Q.X)
  let c := F.mul (F.mul (F.mul P.T 2) d) Q.T
  let dd := F.mul (F.mul P.Z 2) Q.Z
  let e := F.sub b a
  let f := F.sub dd c
  let g := F.add dd c
  let h := F.add b a
  ⟨F.mul e f, F.mul g h, F.mul f g, F.mul e h⟩

/-- Point doubling. -/
def double (P : Point) : Point :=
  let a := F.mul P.X P.X
  let b := F.mul P.Y P.Y
  let c := F.mul 2 (F.mul P.Z P.Z)
  let h := F.add a b
  let e := F.sub h (F.mul (F.add P.X P.Y) (F.add P.X P.Y))
  let g := F.sub a b
  let f := F.add c g
  ⟨F.mul e f, F.mul g h, F.mul f g, F.mul e h⟩

/-- Additive inverse. -/
def neg (P : Point) : Point := ⟨F.neg P.X, P.Y, P.Z, F.neg P.T⟩

/-- Projective equality: `X₁/Z₁ = X₂/Z₂` and `Y₁/Z₁ = Y₂/Z₂`. -/
def eq (P Q : Point) : Bool :=
  F.mul P.X Q.Z == F.mul Q.X P.Z && F.mul P.Y Q.Z == F.mul Q.Y P.Z

/-- The binary digits of `n`, most significant first. -/
def bits (n : Nat) (acc : List Bool) : List Bool :=
  if h : n = 0 then acc
  else bits (n / 2) ((n % 2 == 1) :: acc)
termination_by n
decreasing_by exact Nat.div_lt_self (Nat.pos_of_ne_zero h) (by decide)

/-- Scalar multiplication by double-and-add, most significant bit first. -/
def smul (n : Nat) (P : Point) : Point :=
  (bits n []).foldl (fun acc b => let acc := double acc; if b then add acc P else acc) zero

/-- Affine `y` coordinate together with the parity of `x`, i.e. the data of the
32-byte compressed encoding. -/
def compress (P : Point) : Bytes :=
  let zi := F.inv P.Z
  let x := F.mul P.X zi
  let y := F.mul P.Y zi
  let b := Bytes.ofNatLE 32 y
  let last := b[31]!
  b.set! 31 (if F.isOdd x then last ||| 0x80 else last)

/-- `[8]P = 0`, i.e. `P` lies in the torsion subgroup. -/
def isSmallOrder (P : Point) : Bool := eq (double (double (double P))) zero

end Point

/-- Decompress a 32-byte little-endian encoding of a curve point.

Returns `none` when the encoded `y` is not a canonical field element or when
`x² = (y² - 1)/(d y² + 1)` has no square root. -/
def decompress (b : Bytes) : Option Point := do
  if b.size != 32 then none else
  let n := Bytes.toNatLE b
  let sign := n / 2 ^ 255
  let y := n % 2 ^ 255
  if y ≥ p then none else
  let y2 := F.mul y y
  let u := F.sub y2 1
  let v := F.add (F.mul d y2) 1
  -- candidate square root of u/v, following RFC 8032 §5.1.3
  let v3 := F.mul v (F.mul v v)
  let v7 := F.mul v3 (F.mul v3 v)
  let pow58 := F.pow (F.mul u v7) ((p - 5) / 8)
  let x0 := F.mul (F.mul u v3) pow58
  let check := F.mul v (F.mul x0 x0)
  let x ←
    if check == u then some x0
    else if check == F.neg u then some (F.mul x0 sqrtM1)
    else none
  if x == 0 && sign == 1 then none else
  let x := if (if F.isOdd x then 1 else 0) == sign then x else F.neg x
  some ⟨x, y, 1, F.mul x y⟩

/-- The reason a signature was rejected.  The reference implementation surfaces
a single message for all of these, which is reproduced here. -/
inductive Failure where
  /-- The signature was not 64 bytes long. -/
  | badLength
  /-- The scalar `s` was not canonically reduced modulo the group order. -/
  | nonCanonicalScalar
  /-- `R` or the public key could not be decompressed. -/
  | badPoint
  /-- `R` or the public key had small order. -/
  | smallOrder
  /-- The verification equation did not hold. -/
  | equation
  deriving Repr, DecidableEq

/-- Verify an Ed25519 signature, in the strict sense of RFC 8032 plus the
canonicality and small-order checks performed by the reference implementation. -/
def verify (publicKey message signature : Bytes) : Except Failure Unit := do
  if signature.size != 64 then throw .badLength
  if publicKey.size != 32 then throw .badPoint
  let rBytes := signature.extract 0 32
  let sBytes := signature.extract 32 64
  let s := Bytes.toNatLE sBytes
  if s ≥ L then throw .nonCanonicalScalar
  let some rPoint := decompress rBytes | throw .badPoint
  let some aPoint := decompress publicKey | throw .badPoint
  if rPoint.isSmallOrder || aPoint.isSmallOrder then throw .smallOrder
  let k := Bytes.toNatLE (Sha512.hash (rBytes ++ publicKey ++ message)) % L
  -- expected R = [s]B - [k]A
  let expected := Point.add (Point.smul s Point.base) (Point.neg (Point.smul k aPoint))
  if Point.compress expected == rBytes then pure () else throw .equation

/-! ## Signing -/

/-- Clamp the first half of the expanded secret key, as RFC 8032 prescribes:
the low three bits are cleared so the scalar is a multiple of the cofactor, and
the top bits are fixed so it has a constant bit length. -/
def clamp (h : Bytes) : Nat :=
  let b := h.extract 0 32
  let b := b.set! 0 (b[0]! &&& 248)
  let b := b.set! 31 ((b[31]! &&& 127) ||| 64)
  Bytes.toNatLE b

/-- The public key matching a 32-byte secret key. -/
def publicKeyOfSecret (secret : Bytes) : Option Bytes :=
  if secret.size != 32 then none
  else
    let h := Sha512.hash secret
    some (Point.compress (Point.smul (clamp h) Point.base))

/-- Sign a message with a 32-byte secret key. -/
def sign (secret message : Bytes) : Option Bytes :=
  if secret.size != 32 then none
  else
    let h := Sha512.hash secret
    let a := clamp h
    let seed := h.extract 32 64
    let publicKey := Point.compress (Point.smul a Point.base)
    let r := Bytes.toNatLE (Sha512.hash (seed ++ message)) % L
    let rPoint := Point.compress (Point.smul r Point.base)
    let k := Bytes.toNatLE (Sha512.hash (rPoint ++ publicKey ++ message)) % L
    let s := (r + k * a) % L
    some (rPoint ++ Bytes.ofNatLE 32 s)

end Ed25519
end LeanBiscuit
